[package]
name = "shoes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "shoes"
path = "src/bin/server.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }